### ISSUE TITLE
Add a copy of the license to the repository

### ISSUE THREAD

**Issue by Calinou** [antopilo/VoxelFactory#1]
The asset submission says the asset's license is MIT. Please add a copy of the MIT license to the repository to confirm this :slightly_smiling_face:

**Comment by antopilo** [comment]
> The asset submission says the asset's license is MIT. Please add a copy of the MIT license to the repository to confirm this 🙂

Thank you! I just added the licence. Sorry for the delay.

**Comment by Calinou** [comment]
The asset is now approved: https://godotengine.org/asset-library/asset/420
